In [25]:
import re
import time
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
PATH='C:\\Users\\Fossati\\Desktop\\Tesi\\chromedriver97.exe'
driver = webdriver.Chrome(PATH)

In [64]:
#import korean metadata

In [5]:
meta_ko=pd.read_csv("C:\\Users\\Fossati\\Desktop\\Tesi\\Dati\\Dati_SharedBooks\\Coreano\\Shared_Meta_KO_fin.csv")
meta_ko

,Unnamed: 0,Title,Title_EN,ISBN,Author,Auth_Sugg,Num_Rev_Yes,Num_Rev_ol_Yes,Num_Reviews_Naver,az_EN_link,...,Book_type,Shelves_Yes,Dist_Rat_Cont_Yes,Dist_Rat_Design_Yes,Overall_Rat_Yes,Num_Pages_Yes,Pub_Date_Yes,Overall_Rat_ol_Yes,Pub_Date_Naver,Overall_Rat_Naver
0,0,그리고 아무도 없었다,And there was no one.,9.788938e+12,애거사 크리스티,Agatha Christie,120.0,118.0,620.0,https://www.amazon.it/Then-There-Were-None/dp/...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,"['59%', '22%', '18%', '1%', '1%']","['49%', '28%', '19%', '2%', '2%']",8.6,272.0,2002.0,9.2,2002.05.25,8.70
1,1,봄에 나는 없었다,Absent in spring,9.788955e+12,애거사 크리스티,Agatha Christie,50.0,14.0,207.0,https://www.amazon.com/Absent-Spring-AGATHA-CH...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 영미소설 > 영미 장편소설'],"['58%', '38%', '4%', '0%', '0%']","['58%', '40%', '2%', '0%', '0%']",9.1,268.0,2014.0,9.6,2014.01.30,8.38
2,2,오리엔트 특급 살인,Orient Express Murder,9.788960e+12,애거사 크리스티,Agatha Christie,28.0,289.0,72.0,https://www.amazon.com/Murder-Orient-Express-A...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,"['64%', '32%', '4%', '0%', '0%']","['64%', '32%', '4%', '0%', '0%']",9.2,341.0,2013.0,9.8,2014.11.25,9.44
3,3,딸은 딸이다,Daughter is a daughter.,9.788955e+12,애거사 크리스티,Agatha Christie,13.0,3.0,58.0,https://www.amazon.com/Daughters-Daughter-Othe...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 영미소설 > 영미 장편소설'],"['46%', '38%', '15%', '0%', '0%']","['38%', '46%', '15%', '0%', '0%']",8.5,320.0,2014.0,9.4,2014.05.15,9.41
4,4,ABC 살인사건,ABC murder case,9.788938e+12,애거사 크리스티,Agatha Christie,20.0,7.0,47.0,https://www.amazon.com/b-c-Murders-Hercule-Poi...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,"['50%', '35%', '10%', '5%', '0%']","['30%', '40%', '25%', '5%', '0%']",8.3,282.0,2002.0,9.8,2002.05.25,8.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,130,NaN,Untold Night and Day,NaN,NaN,Bae Suah,NaN,NaN,NaN,https://www.amazon.com/gp/product/B07V3335HK/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,131,NaN,The plotter,NaN,NaN,Un-Su Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/1925603768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,132,NaN,I Have the Right to Destroy Myself,NaN,NaN,Young-ha Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/0156030802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,133,NaN,Diary of a murderer,NaN,NaN,Young-ha Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/1328545423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,134,NaN,Princess Bari,NaN,NaN,Hwang Sok-yong,NaN,NaN,NaN,https://www.amazon.com/gp/product/1859641741/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
meta_ko.columns

Index(['Unnamed: 0', 'Title', 'Title_EN', 'ISBN', 'Author', 'Auth_Sugg',
       'Num_Rev_Yes', 'Num_Rev_ol_Yes', 'Num_Reviews_Naver', 'az_EN_link',
       'gr_EN_link', 'az_IT_link', 'an_IT_link', 'Yes24_link', 'Naver_link',
       'Book_type', 'Shelves_Yes', 'Dist_Rat_Cont_Yes', 'Dist_Rat_Design_Yes',
       'Overall_Rat_Yes', 'Num_Pages_Yes', 'Pub_Date_Yes',
       'Overall_Rat_ol_Yes', 'Pub_Date_Naver', 'Overall_Rat_Naver'],
      dtype='object')

In [7]:
# liste ad hoc 
title=meta_ko['Title'].to_list()
isbn=meta_ko['ISBN'].to_list()
gen=meta_ko['Shelves_Yes'].to_list()
booklist=meta_ko['Yes24_link'].to_list()

nrev_list=meta_ko['Num_Rev_Yes'].to_list()
nrev_list_ol=meta_ko['Num_Rev_ol_Yes'].to_list()

In [10]:
int(4.0)

4

In [11]:
#queste altre liste servono per la prima parte dedicata alle reviews specifiche:
rev_content=[]
rev_ratings=[]
rev_date=[]
userlist=[]
n_likes=[]
#vanno fillate ogn i volta
titoli=[]
isbn_code=[]
genere=[]



#queste altre liste servono per la seconda parte dedicata alle reviews specifiche one line:
rev_content_ol=[]
rev_ratings_ol=[]
rev_date_ol=[]
userlist_ol=[]
n_likes_ol=[]
#vanno fillate ogni volta
titoli_ol=[]
isbn_code_ol=[]
genere_ol=[]

#devo fare in modo che i due dataset siamo separati ma che siano anche unibili in qualsiasi momento

In [40]:
#codice scraping finale yes24


#not_found=[]
numero_libro=0  #-1


for book in booklist:   
    
    time.sleep(2)
    numero_libro+=1
    try:
        try:
            url= str(book)
            driver.get(url)
        except:
            time.sleep(5)
            url= str(book)
            driver.get(url)
    except:
        #no_link+=1
        not_found.append(numero_libro) #cosi sappiamo quali indici di libro perdiamo
        continue

    

    
    
    
    #REVIEWS LUNGHE:
    
    #number of reviews
    try:
        n_rev = driver.find_element_by_id('emReviewCountText').text
        n_rev=int(re.findall(r'\d+', n_rev)[0])
    except:
        n_rev=nrev_list[numero_libro]
    
    
    number=str(int(re.findall(r'\d+', book)[1]))#servirà poi per creare il link
    p1='http://www.yes24.com/Product/communityModules/GoodsReviewList/'
    p2=str(number)
    p3='?Sort=1&PageNumber='
    p5='&Type=ALL'
    
    
    if n_rev > 5: #se le reviews non sono solo ristrette in una pagina
    
        #page_link=driver.find_element_by_xpath("//div[@class='yesUI_pagenS']/a[@class='num']").get_attribute('href')
        #p1=page_link[0:88]  #si scinde il link per poter ciclare il numero di pagina
        #p2=page_link[89:]
        
        
        
        if n_rev//5 == n_rev/5:  #valuta se sono divisibili per 5 
    
            for i in range(1,int(n_rev/5 +1),1):  #5 reviews per pagina
                
                p4= str(i)
                url2=p1+p2+p3+p4+p5
                
                try:
                    try:
                        driver.get(url2)
                    except:
                        time.sleep(5)
                        driver.get(url2)
                except:
                    continue #lo balzi diretto, senza appendere gli errori che tanto poi li vai ad eliminare
                 

                
                
                #fissiamo il paletto di riferimento per le reviews lunghe
                try:
                    try:
                        members_rev=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap reviewRow_cont tp_tab yesComLoadingArea']")
                    except:
                        time.sleep(5) 
                        members_rev=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap reviewRow_cont tp_tab yesComLoadingArea']")
                except:
                    continue
                    
                    
                #cominciamo con il fillare la lista dei titoli, isbn e genere
                titoli.extend([title[numero_libro] for x in range(5)])
                isbn_code.extend([isbn[numero_libro] for x in range(5)])
                genere.extend([gen[numero_libro] for x in range(5)])
                
        
                #data
                try:
                    review_date=members_rev.find_elements_by_class_name('txt_date')
                    for el in review_date:
                        rev_date.append(el.text)
                    time.sleep(1)
            
                except:
                    rev_date.extend(['error' for x in range(5)])
                    time.sleep(2)
        
                #ratings
                try:
                    review_rating = members_rev.find_elements_by_class_name('review_rating') 
                    for el in review_rating:
                        rev_ratings.append(re.findall(r'\d+', el.text))
                    time.sleep(1)
                
                except:
                    rev_ratings.extend(['error' for x in range(5)])
                    time.sleep(2)
                    
                                        
                #n_likes
                
                try:
                    likes=members_rev.find_elements_by_class_name('yes_b.txt')
                    for el in likes:
                        n_likes.append(el.text)
                except:
                    n_likes.extend(['error' for x in range(5)])
            
            

            
                #contenuto
                try:
                    time.sleep(1)
                    review_cont = members_rev.find_elements_by_xpath("//div[@class='reviewInfoGrp lnkExtend']/div[@class='reviewInfoBot origin']/div[@class='review_cont']")
                    for el in review_cont:
                        review_content = el.get_attribute('textContent')
                        rev_content.append(review_content.strip())
                    time.sleep(1)
                
                except:
                    rev_content.extend(['error' for x in range(5)])
                    time.sleep(2)
            
                
                #username review
                try:
                    blog_lnk=driver.find_elements_by_xpath("//div[@class='reviewInfoGrp lnkExtend']/div[@class='reviewInfoBot origin']/div[@class='review_lnk']/p/a")
                    links_blog=[]
                    for el in blog_lnk:
                        links_blog.append(el.get_attribute('href'))
                    for el in links_blog:
                        try:
                            driver.get(str(el))
                            user=driver.find_element_by_id('ImgLayer').text
                            userlist.append(user)
                        except:
                            userlist.append('error')
                except:
                    userlist.append('error')
                    

                
                        
                        
                        
                        
        
        
        else:
            
            
            for i in range(1,int(n_rev/5 +2),1):  #5 reviews per pagina con l'ultima che potrebbe averne chissà quante
                
                p4= str(i)
                url2=p1+p2+p3+p4+p5
                
                try:
                    try:
                        driver.get(url2)
                    except:
                        time.sleep(5)
                        driver.get(url2)
                except:
                    continue #lo balzi diretto, senza appendere gli errori che tanto poi li vai ad eliminare
                 

                
                
                #fissiamo il paletto di riferimento per le reviews lunghe
                try:
                    try:
                        members_rev=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap reviewRow_cont tp_tab yesComLoadingArea']")
                    except:
                        time.sleep(5) 
                        members_rev=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap reviewRow_cont tp_tab yesComLoadingArea']")
                except:
                    continue
                    
                    
                #cominciamo con il fillare la lista dei titoli, isbn e genere
                titoli.extend([title[numero_libro] for x in range(5)])
                isbn_code.extend([isbn[numero_libro] for x in range(5)])
                genere.extend([gen[numero_libro] for x in range(5)])
                
        
                #data
                try:
                    review_date=members_rev.find_elements_by_class_name('txt_date')
                    for el in review_date:
                        rev_date.append(el.text)
                    time.sleep(1)
            
                except:
                    rev_date.extend(['error' for x in range(5)])
                    time.sleep(2)
        
                #ratings
                try:
                    review_rating = members_rev.find_elements_by_class_name('review_rating') 
                    for el in review_rating:
                        rev_ratings.append(re.findall(r'\d+', el.text))
                    time.sleep(1)
                
                except:
                    rev_ratings.extend(['error' for x in range(5)])
                    time.sleep(2)
                    
                                        
                #n_likes
                
                try:
                    likes=members_rev.find_elements_by_class_name('yes_b.txt')
                    for el in likes:
                        n_likes.append(el.text)
                except:
                    n_likes.extend(['error' for x in range(5)])
            
            

            
                #contenuto
                try:
                    time.sleep(1)
                    review_cont = members_rev.find_elements_by_xpath("//div[@class='reviewInfoGrp lnkExtend']/div[@class='reviewInfoBot origin']/div[@class='review_cont']")
                    for el in review_cont:
                        review_content = el.get_attribute('textContent')
                        rev_content.append(review_content.strip())
                    time.sleep(1)
                
                except:
                    rev_content.extend(['error' for x in range(5)])
                    time.sleep(2)
            
                
                #username review
                try:
                    blog_lnk=driver.find_elements_by_xpath("//div[@class='reviewInfoGrp lnkExtend']/div[@class='reviewInfoBot origin']/div[@class='review_lnk']/p/a")
                    links_blog=[]
                    for el in blog_lnk:
                        links_blog.append(el.get_attribute('href'))
                    for el in links_blog:
                        try:
                            driver.get(str(el))
                            user=driver.find_element_by_id('ImgLayer').text
                            userlist.append(user)
                        except:
                            userlist.append('error')
                except:
                    userlist.append('error')
                        
                        
    
    
    
    else: #se le reviews sono 5 o meno, quindi una sola pagina
        
            #fissiamo il paletto di riferimento per le reviews lunghe
            try:
                    try:
                        members_rev=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap reviewRow_cont tp_tab yesComLoadingArea']")
                    except:
                        time.sleep(5) 
                        members_rev=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap reviewRow_cont tp_tab yesComLoadingArea']")
            except:
                    continue
                    
            #cominciamo con il fillare la lista dei titoli, isbn e genere
            titoli.extend([title[numero_libro] for x in range(int(n_rev))])
            isbn_code.extend([isbn[numero_libro] for x in range(int(n_rev))])
            genere.extend([gen[numero_libro] for x in range(int(n_rev))])
        
            #data
            try:
                review_date=members_rev.find_elements_by_class_name('txt_date')
                for el in review_date:
                    rev_date.append(el.text)
                time.sleep(1)
            
            except:
                rev_date.extend(['error' for x in range(n_rev)])
                time.sleep(1)
        
            #ratings
            try:
                review_rating = members_rev.find_elements_by_class_name('review_rating') 
                for el in review_rating:
                    rev_ratings.append(re.findall(r'\d+', el.text))
                time.sleep(1)
                
            except:
                rev_ratings.extend(['error' for x in range(int(n_rev))])
            
                time.sleep(1)
                

            #n_likes
                
            try:
                    likes=members_rev.find_elements_by_class_name('yes_b.txt')
                    for el in likes:
                        n_likes.append(el.text)
            except:
                    n_likes.extend(['error' for x in range(int(n_rev))])            
            

            
            #contenuto
            try:
                review_cont = members_rev.find_elements_by_xpath("//div[@class='reviewInfoGrp lnkExtend']/div[@class='reviewInfoBot origin']/div[@class='review_cont']")
                for el in review_cont:
                    review_content = el.get_attribute('textContent')
                    rev_content.append(review_content.strip())
                time.sleep(1)
                
            except:
                rev_content.extend(['error' for x in range(int(n_rev))])
                time.sleep(1)
            
            
            #username review
            try:
    
                blog_lnk=driver.find_elements_by_xpath("//div[@class='reviewInfoGrp lnkExtend']/div[@class='reviewInfoBot origin']/div[@class='review_lnk']/p/a")
                links_blog=[]
                for el in blog_lnk:
                    links_blog.append(el.get_attribute('href'))
                for el in links_blog:
                    try:
                        driver.get(str(el))
                        user=driver.find_element_by_id('ImgLayer').text
                        userlist.append(user)
                    except:
                        userlist.append('error')
            
            except:
                
                userlist.append('error')

                
    time.sleep(5)
    
    
    
    
    
    
    
    
    
    

    

    
    

    
    
    
    
    
   
                    
                    
                    
    
    #uniformiamo la lunghezza delle liste titoli alla fine di ogni libro:
    titoli=titoli[:len(rev_content)]
    isbn_code=isbn_code[:len(rev_content)]
    genere=genere[:len(rev_content)]
    
    titoli_ol=titoli_ol[:len(rev_content_ol)]
    isbn_code_ol=isbn_code_ol[:len(rev_content_ol)]
    genere_ol=genere_ol[:len(rev_content_ol)]
    
    
    print(numero_libro)
    print(len(titoli))
    print(len(userlist))
    print(len(titoli_ol))
    print(len(userlist_ol))

120
7862
7862
5065
5064
121
8216
8216
5065
5064
122
9034
9034
5065
5064
123
9152
9152
5065
5064
124
9414
9414
5065
5064
125
9463
9463
5065
5064
126
9618
9618
5065
5064
127
10282
10282
5065
5064
128
10623
10623
5065
5064
129
10690
10690
5065
5064
130
10720
10720
5065
5064
131
10728
10728
5065
5064
132
10807
10807
5065
5064
133
11119
11119
5065
5064
134
11367
11367
5065
5064

In [ ]:
#ONE LINE REVIEWS:  #da riagganciare al codice sopra per una raccolta unica


    
    try:
        time.sleep(1)
        url= str(book) #ci riportiamo al punto giusto, a inizio pagina
        driver.get(url)
    except:
        time.sleep(5)
        driver.get(url)
        
    #numero di reviews one line
    n_rev_ol=nrev_list_ol[numero_libro]

    
        
    
    if n_rev_ol > 6: #se le ol reviews non sono solo ristrette in una pagina
    
        try:
            time.sleep(1)
            page_link_ol=driver.find_element_by_xpath("//div[@class='rvCmt_sort']/div[@class='rvCmt_sortLft']/div[@class='yesUI_pagenS']/a[@class='num']").get_attribute('href')
        except:
            time.sleep(5)
            page_link_ol=driver.find_element_by_xpath("//div[@id='infoset_oneCommentList']/div[@class='rvCmt_sort']/div[@class='rvCmt_sortLft']/div[@class='yesUI_pagenS']/a[@class='num']").get_attribute('href')
        
        
        
        if n_rev_ol//6 == n_rev_ol/6:
    
            for i in range(1,int(n_rev_ol/6 +1),1):  #6 reviews per pagina
                
                try:
                    try:
                        url3=page_link_ol[:-1]+str(i)
                        driver.get(url3)
                    except:
                        time.sleep(5)
                        url3=page_link_ol[:-1]+str(i)
                        driver.get(url3)
                except:
                    continue
                 
                try:
                    try:
                        members_rev_ol=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap rvCmtRow_cont clearfix']")
                    except:
                        time.sleep(5)
                        members_rev_ol=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap rvCmtRow_cont clearfix']")
                except:
                    continue

                    
                #cominciamo con il fillare la lista dei titoli, isbn e genere
                titoli_ol.extend([title[numero_libro] for x in range(6)])
                isbn_code_ol.extend([isbn[numero_libro] for x in range(6)])
                genere_ol.extend([gen[numero_libro] for x in range(6)])
        
                #data ol
                try:
                    review_date_ol=members_rev_ol.find_elements_by_class_name('txt_date')
                    for el in review_date_ol:
                        rev_date_ol.append(el.text)
                    time.sleep(1)
            
                except:
                    rev_date_ol.extend(['error' for x in range(6)])
                    time.sleep(1)
                    
                #n_likes
                
                try:
                    likes=members_rev_ol.find_elements_by_class_name('yes_b.txt')
                    for el in likes:
                        n_likes_ol.append(el.text)
                except:
                    n_likes_ol.extend(['error' for x in range(6)])
        
                #ratings ol
                try:
                    review_rating_ol = members_rev_ol.find_elements_by_class_name('cmt_rating') 
                    for el in review_rating_ol:
                        rev_ratings_ol.append(re.findall(r'\d+', el.text))
                    time.sleep(1)
                
                except:
                    rev_ratings_ol.extend(['error' for x in range(6)])
                    time.sleep(1)
            
            
                #contenuto ol
                try:
                    review_cont_ol = members_rev_ol.find_elements_by_xpath("//div[@class='cmtInfoBox']/div[@class='cmt_cont']/span[@class='txt']")
                    for el in review_cont_ol:
                        review_content_ol = el.text
                        rev_content_ol.append(review_content_ol)
                    time.sleep(1)
                
                except:
                    rev_content_ol.extend(['error' for x in range(6)])
                    time.sleep(1)
            
                #username review oneline
        
                user_ol=driver.find_elements_by_class_name('lnk_nick')
                for el in user_ol:
                    try:
                        userlist_ol.append(el.text)
                    except:
                        userlist_ol.append('error')
                        
        
        
                        
                        
        
        
        else:
            
            for i in range(1,int(n_rev_ol/6 +2),1):  #6 reviews per pagina
                
                try:
                    try:
                        url3=page_link_ol[:-1]+str(i)
                        driver.get(url3)
                    except:
                        time.sleep(5)
                        url3=page_link_ol[:-1]+str(i)
                        driver.get(url3)
                except:
                    continue
                 
                try:
                    try:
                        members_rev_ol=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap rvCmtRow_cont clearfix']")
                    except:
                        time.sleep(5)
                        members_rev_ol=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap rvCmtRow_cont clearfix']")
                except:
                    continue

                    
                #cominciamo con il fillare la lista dei titoli, isbn e genere
                titoli_ol.extend([title[numero_libro] for x in range(6)])
                isbn_code_ol.extend([isbn[numero_libro] for x in range(6)])
                genere_ol.extend([gen[numero_libro] for x in range(6)])
        
                #data ol
                try:
                    review_date_ol=members_rev_ol.find_elements_by_class_name('txt_date')
                    for el in review_date_ol:
                        rev_date_ol.append(el.text)
                    time.sleep(1)
            
                except:
                    rev_date_ol.extend(['error' for x in range(6)])
                    time.sleep(1)
                    
                #n_likes
                
                try:
                    likes=members_rev_ol.find_elements_by_class_name('yes_b.txt')
                    for el in likes:
                        n_likes_ol.append(el.text)
                except:
                    n_likes_ol.extend(['error' for x in range(6)])
        
                #ratings ol
                try:
                    review_rating_ol = members_rev_ol.find_elements_by_class_name('cmt_rating') 
                    for el in review_rating_ol:
                        rev_ratings_ol.append(re.findall(r'\d+', el.text))
                    time.sleep(1)
                
                except:
                    rev_ratings_ol.extend(['error' for x in range(6)])
                    time.sleep(1)
            
            
                #contenuto ol
                try:
                    review_cont_ol = members_rev_ol.find_elements_by_xpath("//div[@class='cmtInfoBox']/div[@class='cmt_cont']/span[@class='txt']")
                    for el in review_cont_ol:
                        review_content_ol = el.text
                        rev_content_ol.append(review_content_ol)
                    time.sleep(1)
                
                except:
                    rev_content_ol.extend(['error' for x in range(6)])
                    time.sleep(1)
            
                #username review oneline
        
                user_ol=driver.find_elements_by_class_name('lnk_nick')
                for el in user_ol:
                    try:
                        userlist_ol.append(el.text)
                    except:
                        userlist_ol.append('error')                      
                        
    
    
    
    else:   #se c'è solo una pagina in cui prendere i dati
            
                 
            try:
                    try:
                        members_rev_ol=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap rvCmtRow_cont clearfix']")
                    except:
                        time.sleep(5)
                        members_rev_ol=driver.find_element_by_xpath("//div[@class='infoSetCont_wrap rvCmtRow_cont clearfix']")
            except:
                    continue
                    
                    
                    
            #cominciamo con il fillare la lista dei titoli, isbn e genere
            titoli_ol.extend([title[numero_libro] for x in range(int(n_rev_ol))])
            isbn_code_ol.extend([isbn[numero_libro] for x in range(int(n_rev_ol))])
            genere_ol.extend([gen[numero_libro] for x in range(int(n_rev_ol))])
                    
                    
            
            #data ol
            try:
                review_date_ol=members_rev_ol.find_elements_by_class_name('txt_date')
                for el in review_date_ol:
                    rev_date_ol.append(el.text)
                time.sleep(1)
            
            except:
                rev_date_ol.extend(['error' for x in range(int(n_rev_ol))])
                time.sleep(1)
        
            #ratings ol
            try:
                review_rating_ol = members_rev_ol.find_elements_by_class_name('cmt_rating') 
                for el in review_rating_ol:
                    rev_ratings_ol.append(re.findall(r'\d+', el.text))
                time.sleep(1)
                
            except:
                rev_ratings_ol.extend(['error' for x in range(int(n_rev_ol))])
                time.sleep(1)
                
            
            #n_likes
                
            try:
                    likes=members_rev_ol.find_elements_by_class_name('yes_b.txt')
                    for el in likes:
                        n_likes_ol.append(el.text)
            except:
                    n_likes_ol.extend(['error' for x in range(int(n_rev_ol))])
            
            
            
            #contenuto ol
            try:
                review_cont_ol = members_rev_ol.find_elements_by_xpath("//div[@class='cmtInfoBox']/div[@class='cmt_cont']/span[@class='txt']")
                for el in review_cont_ol:
                    review_content_ol = el.text
                    rev_content_ol.append(review_content_ol)
                time.sleep(1)
                
            except:
                rev_content_ol.extend(['error' for x in range(int(n_rev_ol))])
                time.sleep(1)
            
            
            
            #username review oneline
            
            try:
                user_ol=driver.find_elements_by_class_name('lnk_nick')
                for el in user_ol:
                    try:
                        userlist_ol.append(el.text)
                    except:
                        userlist_ol.append('error')
            except:
                userlist_ol.append('error')

In [43]:
print(len(rev_content))
print(len(titoli))
print(len(genere))
print(len(rev_ratings))
print(len(rev_date))
print(len(isbn_code))
print(len(userlist))
print(len(n_likes))

11367
11367
11367
11367
11372
11367
11367
11367

In [44]:
print(len(rev_content_ol))
print(len(genere_ol))
print(len(rev_ratings_ol))
print(len(rev_date_ol))
print(len(titoli_ol))
print(len(userlist_ol))
print(len(isbn_code_ol))
print(len(n_likes_ol))

5065
5065
5064
5064
5065
5064
5065
5064

In [45]:
#REVIEWS LUNGHE

reviews=pd.DataFrame(list(zip(genere,titoli,isbn_code,userlist,rev_date,rev_ratings,n_likes,rev_content)), columns=['Genere','Title','ISBN','Username','Review_Date','Review_Ratings','Num_Likes','Review_Content'])
reviews=reviews.reset_index()
#affil_covid_def=affil_covid_def.drop('index',axis=1)
reviews

,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content
0,0,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,백발마녀,2021-12-08,"[1, 1]",0,너무불필요한 ㅡㅡㅡ이런표시들이 너무많아서 몰입이안되요내가 어렸을때 너무재미있게읽은책...
1,1,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,aerigy,2021-10-18,"[4, 3]",0,워낙 유명한 책이여서 궁금해서 이번에 구매하고 읽었는데 저한테는 엄청나게 재밌진 않...
2,2,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,전보승,2021-08-15,"[5, 5]",0,애거서 크리스티의 유명한 작품. 그리고 아무도 없었다.\n\n줄거리.\n\n은퇴한 ...
3,3,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,천가이,2021-07-22,"[5, 5]",0,"<그리고 아무도 없었다>는 1939년에 처음 출간된, 추리소설의 여왕 아가사 크리스..."
4,4,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,보라보라,2021-05-08,"[3, 3]",0,이 책은 법의 손길이 닿지않는 범죄를 저리른 사람들에대한 이야기가 담겨있다.\n어느...
...,...,...,...,...,...,...,...,...,...
11362,11362,NaN,NaN,NaN,솔이마루마마,2007-07-08,"[5, 5]",13,"바리데기 - 황석영\n아,,,뭐라 할까.그냥 감동적이다.라고 하기엔 나의 표현력이 ..."
11363,11363,NaN,NaN,NaN,진달래,2007-07-06,"[5, 5]",53,"정말 아름다운 작품이다. <오래된 정원>의 강렬한 사랑과 이념의 정수 이후, 진흙 ..."
11364,11364,NaN,NaN,NaN,romee21,2007-07-05,"[5, 4]",1,가제본된 책을 받는 순간 온몸에 떨림이 전해져 왔다. 마치 영화 시나리오를 받은 신...
11365,11365,NaN,NaN,NaN,노부타,2007-07-05,"[4, 4]",0,어릴적에 그리스 로마 신화를 수십번도 더 읽은 기억이 있습니다. \n하지만 바리데기...
11366,11366,NaN,NaN,NaN,삼지닥나무,2007-07-05,"[5, 4]",27,좋은 책을 미리 만나게 되서 좋았습니다. 받자마자 바로 읽기 시작했는데\n손을 놓을...

In [48]:
reviews[reviews['Review_Content']=='error']

,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content
830,830,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 공포/스릴러\n ...,인페르노 1,9.788984e+12,북뉴스조나단,2016-10-21,"[4, 4]",0,error
831,831,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 공포/스릴러\n ...,인페르노 1,9.788984e+12,error,2016-10-16,"[3, 1]",0,error
832,832,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 공포/스릴러\n ...,인페르노 1,9.788984e+12,sue0214,2016-10-10,"[5, 5]",0,error
833,833,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 공포/스릴러\n ...,인페르노 1,9.788984e+12,scsvzxc,2016-10-04,"[5, 5]",0,error
834,834,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 공포/스릴러\n ...,인페르노 1,9.788984e+12,error,2016-10-04,"[5, 5]",0,error

In [46]:
#REVIEWS ONELINE

reviews_ol=pd.DataFrame(list(zip(genere_ol,titoli_ol,isbn_code_ol,userlist_ol,rev_date_ol,rev_ratings_ol,n_likes_ol,rev_content_ol)), columns=['Genere','Title','ISBN','Username_ol','Review_Date_ol','Review_Ratings_ol','Num_Likes_ol','Review_Content_ol'])
reviews_ol=reviews_ol.reset_index()
#affil_covid_def=affil_covid_def.drop('index',axis=1)
reviews_ol

,index,Genere,Title,ISBN,Username_ol,Review_Date_ol,Review_Ratings_ol,Num_Likes_ol,Review_Content_ol
0,0,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,또*,2022-01-04,[5],0,유명하다고 해서 사봤는데 기대되네요
1,1,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,i*****l,2021-12-03,[5],0,250개 언어로 번역된 추리소설답게 읽는 데에 막힘이 없었다.
2,2,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,a****y,2021-10-18,[4],0,재밌어요
3,3,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,b********1,2021-10-12,[5],0,재미있게 읽을 수 있을 것 같아요!
4,4,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,h********h,2021-09-22,[5],0,기대됩니다!
...,...,...,...,...,...,...,...,...,...
5059,5059,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,자*,2018-10-11,[5],0,SF의 고전답다. 사이버펑크의 음울한 분위기와 감각적 혼란을 너무 잘 그린 듯. 강추!
5060,5060,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,x***y,2017-12-19,[5],0,본격 SF 고전에 입문해보렵니다.
5061,5061,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,b***n,2017-11-01,[4],0,추천받고 구매하였습니다.
5062,5062,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,멍*,2015-07-08,[5],1,집중이 잘 되지는 않지만 고전이라니...
5063,5063,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,b*****4,2015-04-22,[4],0,고전은 괜히 고전이 아닌 책입니다.

In [47]:
reviews_ol[reviews_ol['Review_Content_ol']=='error']

Empty DataFrame
Columns: [index, Genere, Title, ISBN, Username_ol, Review_Date_ol, Review_Ratings_ol, Num_Likes_ol, Review_Content_ol]
Index: []

In [ ]:
#numero di recensioni = numero di voti

In [49]:
not_found #non ci sono libri non trovati

[]

In [50]:
#numero di recensioni = numero di voti

#controllo duplicati
reviews2=reviews.drop_duplicates( subset=['Title','Review_Content','Username'],keep='first',inplace=False)
reviews2 #amzon ita filtrato dalle righe duplicate

,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content
0,0,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,백발마녀,2021-12-08,"[1, 1]",0,너무불필요한 ㅡㅡㅡ이런표시들이 너무많아서 몰입이안되요내가 어렸을때 너무재미있게읽은책...
1,1,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,aerigy,2021-10-18,"[4, 3]",0,워낙 유명한 책이여서 궁금해서 이번에 구매하고 읽었는데 저한테는 엄청나게 재밌진 않...
2,2,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,전보승,2021-08-15,"[5, 5]",0,애거서 크리스티의 유명한 작품. 그리고 아무도 없었다.\n\n줄거리.\n\n은퇴한 ...
3,3,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,천가이,2021-07-22,"[5, 5]",0,"<그리고 아무도 없었다>는 1939년에 처음 출간된, 추리소설의 여왕 아가사 크리스..."
4,4,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,보라보라,2021-05-08,"[3, 3]",0,이 책은 법의 손길이 닿지않는 범죄를 저리른 사람들에대한 이야기가 담겨있다.\n어느...
...,...,...,...,...,...,...,...,...,...
11362,11362,NaN,NaN,NaN,솔이마루마마,2007-07-08,"[5, 5]",13,"바리데기 - 황석영\n아,,,뭐라 할까.그냥 감동적이다.라고 하기엔 나의 표현력이 ..."
11363,11363,NaN,NaN,NaN,진달래,2007-07-06,"[5, 5]",53,"정말 아름다운 작품이다. <오래된 정원>의 강렬한 사랑과 이념의 정수 이후, 진흙 ..."
11364,11364,NaN,NaN,NaN,romee21,2007-07-05,"[5, 4]",1,가제본된 책을 받는 순간 온몸에 떨림이 전해져 왔다. 마치 영화 시나리오를 받은 신...
11365,11365,NaN,NaN,NaN,노부타,2007-07-05,"[4, 4]",0,어릴적에 그리스 로마 신화를 수십번도 더 읽은 기억이 있습니다. \n하지만 바리데기...
11366,11366,NaN,NaN,NaN,삼지닥나무,2007-07-05,"[5, 4]",27,좋은 책을 미리 만나게 되서 좋았습니다. 받자마자 바로 읽기 시작했는데\n손을 놓을...

In [51]:
#controllo duplicati
reviews_ol2=reviews_ol.drop_duplicates( subset=['Title','Review_Content_ol'],keep='first',inplace=False)
reviews_ol2 #amzon ita filtrato dalle righe duplicate

,index,Genere,Title,ISBN,Username_ol,Review_Date_ol,Review_Ratings_ol,Num_Likes_ol,Review_Content_ol
0,0,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,또*,2022-01-04,[5],0,유명하다고 해서 사봤는데 기대되네요
1,1,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,i*****l,2021-12-03,[5],0,250개 언어로 번역된 추리소설답게 읽는 데에 막힘이 없었다.
2,2,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,a****y,2021-10-18,[4],0,재밌어요
3,3,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,b********1,2021-10-12,[5],0,재미있게 읽을 수 있을 것 같아요!
4,4,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,h********h,2021-09-22,[5],0,기대됩니다!
...,...,...,...,...,...,...,...,...,...
5059,5059,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,자*,2018-10-11,[5],0,SF의 고전답다. 사이버펑크의 음울한 분위기와 감각적 혼란을 너무 잘 그린 듯. 강추!
5060,5060,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,x***y,2017-12-19,[5],0,본격 SF 고전에 입문해보렵니다.
5061,5061,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,b***n,2017-11-01,[4],0,추천받고 구매하였습니다.
5062,5062,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,멍*,2015-07-08,[5],1,집중이 잘 되지는 않지만 고전이라니...
5063,5063,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,b*****4,2015-04-22,[4],0,고전은 괜히 고전이 아닌 책입니다.

In [52]:
reviews2=reviews2.reset_index()
reviews_ol2=reviews_ol2.reset_index()

In [53]:
#selezione lingua corretta
from langdetect import detect
lang=[]
for index, row in reviews2['Review_Content'].iteritems():
    try:
        language = detect(row) #detecting each row
        lang.append(language)
    except:
        lang.append('not found')
print(lang[:10])

ind=[]
count=0
for el in lang:
    if el != 'ko':
        ind.append(count)
    count+=1
print(ind)

['ko', 'ko', 'ko', 'ko', 'ko', 'ko', 'ko', 'ko', 'ko', 'ko']
[34, 820, 1955, 4014]

In [54]:
r=reviews2['Review_Content'].to_list()
r[2007]

"'레지던트 이블'에서 여 주인공은 좀비월드를 벗어나도 다음 편에서는 또다른 좀비존에서 깨어난다. 마치 그녀처럼 '메이즈 러너'에서 죽도록 달렸던 토머스는 또 다시 창조자들의 실험용 쥐로 깨어났다. 짜증스럽게도. 그의 기억은 여전히 불안정 했으며, 텔레파시로 이어진 영혼의 짝 테리사는 사라졌다. \n\xa0\np12 톰, 뭔가 잘못됐어.\n\xa0\n라는 마지막 말을 남기고선. 잘못된 것이 맞다. 기억을 잃고 공터로 내던져진 순간부터 그의 운명은 잘못된 운명으로 던져졌다. 그리고 이번에는 광인들이 가득한 지역. 그들 그룹과 같은 실험을 했다는 다른 그룹에서 살아남은 에어리스까지 포함해서 소년들은 이번존에서도 살아남기 위해 달리고 살피고 의심하고 힘을 합해야만 했다. 무엇이 진실이고 누가 거짓말을 내뱉는지 모르는 가운데. \n\xa0\n태양폭발 이후, 세상이 도대체 어떻게 변해버렸기에 어른들은 청소년들을 대상으로 살아남는 실험을 하게 된 것일까. 생존 능력외에도 더 큰 그림을 그리고 있다는 단체, '사악'. 그들은 태양 플레어로 인해 황폐해진 지구에 희망의 씨를 틔우기 위해 뛰어난 아이들을 길러 시험에 투입했다. 2번째 실험에서 동기 부여를 위해 일부러 플레어 바이러스에 감염시키고 2주 내 피난처에 도착한다면 치료제를 투입하겠다고 약속했다. 그들을 믿어도 될까?\n\xa0\n뇌를 파괴시키고 미치게 만드는 병인 플레어 바이러스. 정북 방향으로 160킬로미터를 이동하는 동안 이 바이러스에 걸려 인간성을 잃어버린 광인들을 소년들은 너무 많이 봤다. 그 끔찍한 모습이 되지 않기 위해 전진하던 토머스는 민호그룹과 헤어지게 되고 테리사의 음모에 제대로 걸려들었다. 배신자. 가장 믿었던 친구의 배신은 한번으로 그치지 않았다. \n\xa0\np 503\xa0\xa0 앞으로 너한테 안 좋은 일이 일어날 거야.(브렌다)\np 508\xa0\xa0\xa0너한테 해 줄 말이 있어, 톰. 사악을 선해. (테리사)\n\xa0\n꺼져. 텔레파시를 받은 톰은 테리사를 향해 사악에게 전할 말을 외치면서 분노했다. 시험이 끝나지 않았음을 알게 되었기 때문이다. 인류의 미래를 걱정한다는 '사악'은 정말 선한 존재일까. 1권과 2권에서 기억을 잃었던 그들의 기억을 되돌리려 하고 있다. 그 삭제 된 기억 속에 어떤 비밀이 숨겨져 있는 것일까. 그리고 마지막으로 사악이 그들 앞에 내던진 진실은 무엇일까. 이 소설 어떻게 끝날지 정말 알 수가 없다. 짐작조차 할 수 없어서 남은 3권이 참으로 짧게 느껴진다. 거대한 스케일의 한 소설 시리즈를 종결짓기에는-."

In [55]:
#valuta se mandarlo
reviews3=reviews2.drop(ind,axis=0).drop('level_0',axis=1).reset_index()
reviews3

,level_0,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content
0,0,0,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,백발마녀,2021-12-08,"[1, 1]",0,너무불필요한 ㅡㅡㅡ이런표시들이 너무많아서 몰입이안되요내가 어렸을때 너무재미있게읽은책...
1,1,1,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,aerigy,2021-10-18,"[4, 3]",0,워낙 유명한 책이여서 궁금해서 이번에 구매하고 읽었는데 저한테는 엄청나게 재밌진 않...
2,2,2,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,전보승,2021-08-15,"[5, 5]",0,애거서 크리스티의 유명한 작품. 그리고 아무도 없었다.\n\n줄거리.\n\n은퇴한 ...
3,3,3,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,천가이,2021-07-22,"[5, 5]",0,"<그리고 아무도 없었다>는 1939년에 처음 출간된, 추리소설의 여왕 아가사 크리스..."
4,4,4,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,보라보라,2021-05-08,"[3, 3]",0,이 책은 법의 손길이 닿지않는 범죄를 저리른 사람들에대한 이야기가 담겨있다.\n어느...
...,...,...,...,...,...,...,...,...,...,...
9153,9157,11362,NaN,NaN,NaN,솔이마루마마,2007-07-08,"[5, 5]",13,"바리데기 - 황석영\n아,,,뭐라 할까.그냥 감동적이다.라고 하기엔 나의 표현력이 ..."
9154,9158,11363,NaN,NaN,NaN,진달래,2007-07-06,"[5, 5]",53,"정말 아름다운 작품이다. <오래된 정원>의 강렬한 사랑과 이념의 정수 이후, 진흙 ..."
9155,9159,11364,NaN,NaN,NaN,romee21,2007-07-05,"[5, 4]",1,가제본된 책을 받는 순간 온몸에 떨림이 전해져 왔다. 마치 영화 시나리오를 받은 신...
9156,9160,11365,NaN,NaN,NaN,노부타,2007-07-05,"[4, 4]",0,어릴적에 그리스 로마 신화를 수십번도 더 읽은 기억이 있습니다. \n하지만 바리데기...
9157,9161,11366,NaN,NaN,NaN,삼지닥나무,2007-07-05,"[5, 4]",27,좋은 책을 미리 만나게 되서 좋았습니다. 받자마자 바로 읽기 시작했는데\n손을 놓을...

In [ ]:
#one line

In [56]:
#selezione lingua corretta
from langdetect import detect
lang=[]
for index, row in reviews_ol2['Review_Content_ol'].iteritems():
    try:
        language = detect(row) #detecting each row
        lang.append(language)
    except:
        lang.append('not found')
print(lang[:10])

ind=[]
count=0
for el in lang:
    if el != 'ko':
        ind.append(count)
    count+=1
print(ind[:3])

#reviews_ol2['Review_Content_ol'][6776]  

reviews_ol3=reviews_ol2.drop(ind,axis=0).drop('level_0',axis=1).reset_index()
reviews_ol3

['ko', 'ko', 'ko', 'ko', 'ko', 'ko', 'ko', 'ko', 'ko', 'ko']
[708, 717, 890]

,level_0,index,Genere,Title,ISBN,Username_ol,Review_Date_ol,Review_Ratings_ol,Num_Likes_ol,Review_Content_ol
0,0,0,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,또*,2022-01-04,[5],0,유명하다고 해서 사봤는데 기대되네요
1,1,1,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,i*****l,2021-12-03,[5],0,250개 언어로 번역된 추리소설답게 읽는 데에 막힘이 없었다.
2,2,2,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,a****y,2021-10-18,[4],0,재밌어요
3,3,3,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,b********1,2021-10-12,[5],0,재미있게 읽을 수 있을 것 같아요!
4,4,4,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,그리고 아무도 없었다,9.788938e+12,h********h,2021-09-22,[5],0,기대됩니다!
...,...,...,...,...,...,...,...,...,...,...
4740,4750,5059,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,자*,2018-10-11,[5],0,SF의 고전답다. 사이버펑크의 음울한 분위기와 감각적 혼란을 너무 잘 그린 듯. 강추!
4741,4751,5060,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,x***y,2017-12-19,[5],0,본격 SF 고전에 입문해보렵니다.
4742,4752,5061,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,b***n,2017-11-01,[4],0,추천받고 구매하였습니다.
4743,4753,5062,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,멍*,2015-07-08,[5],1,집중이 잘 되지는 않지만 고전이라니...
4744,4754,5063,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,뉴로맨서,9.788983e+12,b*****4,2015-04-22,[4],0,고전은 괜히 고전이 아닌 책입니다.

In [ ]:
#pipeline:

#filtraggio duplicati ed errori
#uniamo i file ol e lunghe
#teniuamo tutte senza fare filtro dato che abbiamo pochi libri
#uniamo colonna titolo inglese
#pulizia del genere shelves
#pulizia reviews se serve

In [ ]:
#unione file

In [137]:
reviews_ol3.columns

Index(['level_0', 'index', 'Genere', 'Title', 'ISBN', 'Username_ol',
       'Review_Date_ol', 'Review_Ratings_ol', 'Num_Likes_ol',
       'Review_Content_ol'],
      dtype='object')

In [138]:
reviews3.columns

Index(['level_0', 'index', 'Genere', 'Title', 'ISBN', 'Username',
       'Review_Date', 'Review_Ratings', 'Num_Likes', 'Review_Content'],
      dtype='object')

In [139]:
yesol = reviews_ol3.rename(columns={'Username_ol': 'Username', 'Review_Date_ol': 'Review_Date','Review_Ratings_ol': 'Review_Ratings', 'Num_Likes_ol': 'Num_Likes','Review_Content_ol':'Review_Content'})
print(yesol.columns)




union_yes=pd.concat([reviews3,yesol])
union_yes=union_yes.drop(['level_0','index'],axis=1)
union_yes2=union_yes.sort_values(by=['Title'],ascending=False)
union_yes2=union_yes2.reset_index()
union_yes2

Index(['level_0', 'index', 'Genere', 'Title', 'ISBN', 'Username',
       'Review_Date', 'Review_Ratings', 'Num_Likes', 'Review_Content'],
      dtype='object')

,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content
0,3396,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,yania1207,2008-06-18,"[5, 5]",0,책이 원작인줄 모르고 몇년 전 같은제목의 영화를 봤고 나름 꽤 재미있게 본 탓...
1,3395,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,mort,2009-04-21,"[4, 1]",15,책은 무척 재미있습니다! 하지만 2권 끝의 감상평은 3권까지 다 읽기 전에 \n절대...
2,3394,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,freebird,2009-05-12,"[5, 3]",4,"주말에 잡자 마자 세 권을 읽을 수 밖에 없었다. 음... 해리 포터, 잃어버린 책..."
3,3393,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,soul79,2009-05-16,"[5, 2]",10,"그동안 많은 책과 소설을 읽어보았지만, 어린이를 위한 판타지 소설치고 이 책만큼 도..."
4,3392,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,동원참치,2009-05-17,"[3, 3]",0,드디어 다 읽었다. 판타지 소설이라 일반소설책보다는 좀 쉽게쉽게 읽어진감이 없지않아...
...,...,...,...,...,...,...,...,...,...
13898,9153,NaN,NaN,NaN,솔이마루마마,2007-07-08,"[5, 5]",13,"바리데기 - 황석영\n아,,,뭐라 할까.그냥 감동적이다.라고 하기엔 나의 표현력이 ..."
13899,9154,NaN,NaN,NaN,진달래,2007-07-06,"[5, 5]",53,"정말 아름다운 작품이다. <오래된 정원>의 강렬한 사랑과 이념의 정수 이후, 진흙 ..."
13900,9155,NaN,NaN,NaN,romee21,2007-07-05,"[5, 4]",1,가제본된 책을 받는 순간 온몸에 떨림이 전해져 왔다. 마치 영화 시나리오를 받은 신...
13901,9156,NaN,NaN,NaN,노부타,2007-07-05,"[4, 4]",0,어릴적에 그리스 로마 신화를 수십번도 더 읽은 기억이 있습니다. \n하지만 바리데기...
13902,9157,NaN,NaN,NaN,삼지닥나무,2007-07-05,"[5, 4]",27,좋은 책을 미리 만나게 되서 좋았습니다. 받자마자 바로 읽기 시작했는데\n손을 놓을...

In [ ]:
#check errori

In [140]:
union_yes2[union_yes2['Review_Content']=='error']

Empty DataFrame
Columns: [index, Genere, Title, ISBN, Username, Review_Date, Review_Ratings, Num_Likes, Review_Content]
Index: []

In [141]:
union_yes2[union_yes2['Review_Content']=='[]']

Empty DataFrame
Columns: [index, Genere, Title, ISBN, Username, Review_Date, Review_Ratings, Num_Likes, Review_Content]
Index: []

In [142]:
union_yes2[union_yes2['Review_Content']=='']

Empty DataFrame
Columns: [index, Genere, Title, ISBN, Username, Review_Date, Review_Ratings, Num_Likes, Review_Content]
Index: []

In [ ]:
#a posto, già puliti separatemaente per lingua ed errori vari

In [ ]:
#UNIONE COLONNA TITOLO EN

In [143]:
titen=meta_ko[['Title','Title_EN']]
to9915=pd.merge(union_yes2[:9915], titen, on = 'Title', how='left')
to9915

,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content,Title_EN
0,3396,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,yania1207,2008-06-18,"[5, 5]",0,책이 원작인줄 모르고 몇년 전 같은제목의 영화를 봤고 나름 꽤 재미있게 본 탓...,Golden or invasion set
1,3395,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,mort,2009-04-21,"[4, 1]",15,책은 무척 재미있습니다! 하지만 2권 끝의 감상평은 3권까지 다 읽기 전에 \n절대...,Golden or invasion set
2,3394,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,freebird,2009-05-12,"[5, 3]",4,"주말에 잡자 마자 세 권을 읽을 수 밖에 없었다. 음... 해리 포터, 잃어버린 책...",Golden or invasion set
3,3393,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,soul79,2009-05-16,"[5, 2]",10,"그동안 많은 책과 소설을 읽어보았지만, 어린이를 위한 판타지 소설치고 이 책만큼 도...",Golden or invasion set
4,3392,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 판타지\n 국내...,황금나침반 세트,9.788935e+12,동원참치,2009-05-17,"[3, 3]",0,드디어 다 읽었다. 판타지 소설이라 일반소설책보다는 좀 쉽게쉽게 읽어진감이 없지않아...,Golden or invasion set
...,...,...,...,...,...,...,...,...,...,...
9910,3512,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,제****마,2017-06-28,[5],0,"몇몇 스티븐 킹 님 작품이 용두사미 성향이라 좀 걱정스럽기는하지만, 1권 현재까지는...",11/22/63 1
9911,3511,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,k*****t,2020-01-14,[5],0,장황하고 산만해서 스티븐킹을 별로 안좋아하는데 이건 그나마 읽을만했다,11/22/63 1
9912,3936,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,구르믈버서난달,2012-12-26,"[4, 3]",0,공포소설의 거장 스티븐 킹의 신작 '11/22/63'입니다. 스티븐 킹의 창작력은 ...,11/22/63 1
9913,3938,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,몽상가,2012-12-20,"[5, 4]",0,"젠장, 이 책을 집어 드는 게 아니었어!\n‘스티븐 킹’의 신간 <11/22/63>...",11/22/63 1
9914,3926,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,NYLiverpool,2013-03-23,"[5, 5]",0,앨스 다이너를 운영하는 앨 템플턴이 있다. 그리고 고등학교에서 작문숙제를 내고 검토...,11/22/63 1

In [144]:
#questa è la porzione di dataframe relativa ai Nan
novalue=union_yes2[9915:]
novalue

,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content
9915,5170,NaN,NaN,NaN,RSsun,2012-12-10,"[5, 5]",0,"인상깊은 구절\n\n산다는 것은 이상한 일이라고, 그 웃음의 끝에 그녀는 생각한다...."
9916,5171,NaN,NaN,NaN,kalavinka,2011-03-22,"[4, 4]",0,"언론에서 ""맨부커 인터내셔널 상""과 관련하여 이슈가 되었던 도서라 구입하게 되었습니..."
9917,5172,NaN,NaN,NaN,자미원국,2009-01-11,"[4, 5]",0,우선 작가의 사진이 다른 책보다 크다.\n\n무게감도 있지만 느낌이 좋다.\n\n무...
9918,5173,NaN,NaN,NaN,설탕,2008-12-17,"[4, 4]",0,정말로 유명한 책.\n\n채식주의자가 세상에 나온지는 아주. 아주 꽤 된 것 같은데...
9919,5174,NaN,NaN,NaN,secret,2005-11-04,"[5, 5]",1,과거 맨부커상 수상에 대한 수많은 기사와 뉴스에서 본 그 작품이기에 낯익은 듯 낯설...
...,...,...,...,...,...,...,...,...,...
13898,9153,NaN,NaN,NaN,솔이마루마마,2007-07-08,"[5, 5]",13,"바리데기 - 황석영\n아,,,뭐라 할까.그냥 감동적이다.라고 하기엔 나의 표현력이 ..."
13899,9154,NaN,NaN,NaN,진달래,2007-07-06,"[5, 5]",53,"정말 아름다운 작품이다. <오래된 정원>의 강렬한 사랑과 이념의 정수 이후, 진흙 ..."
13900,9155,NaN,NaN,NaN,romee21,2007-07-05,"[5, 4]",1,가제본된 책을 받는 순간 온몸에 떨림이 전해져 왔다. 마치 영화 시나리오를 받은 신...
13901,9156,NaN,NaN,NaN,노부타,2007-07-05,"[4, 4]",0,어릴적에 그리스 로마 신화를 수십번도 더 읽은 기억이 있습니다. \n하지만 바리데기...
13902,9157,NaN,NaN,NaN,삼지닥나무,2007-07-05,"[5, 4]",27,좋은 책을 미리 만나게 되서 좋았습니다. 받자마자 바로 읽기 시작했는데\n손을 놓을...

In [100]:
titolinan=meta_ko[120:]['Title_EN'].tolist()
titolinan

['The Vegetarian',
 'Human acts',
 'Please look after mom',
 'The court dancer',
 'I’ll be right there',
 'Pachinko',
 'The Hen Who Dreamed She Could Fly',
 'Kim Jiyoung, Born 1982',
 'The good son',
 'The investigation',
 'Untold Night and Day',
 'The plotter',
 'I Have the Right to Destroy Myself',
 'Diary of a murderer',
 'Princess Bari']

In [149]:
linan=[]
count=0
for i in range (0,15):
    for j in range (1,266):
        linan.append(titolinan[i])
        
    if i<13:
        linan.append(titolinan[i])
                
print(len(linan))

3988

In [150]:
novalue['Title_EN']=linan
novalue

<ipython-input-150-acc192a0cabd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  novalue['Title_EN']=linan

,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content,Title_EN
9915,5170,NaN,NaN,NaN,RSsun,2012-12-10,"[5, 5]",0,"인상깊은 구절\n\n산다는 것은 이상한 일이라고, 그 웃음의 끝에 그녀는 생각한다....",The Vegetarian
9916,5171,NaN,NaN,NaN,kalavinka,2011-03-22,"[4, 4]",0,"언론에서 ""맨부커 인터내셔널 상""과 관련하여 이슈가 되었던 도서라 구입하게 되었습니...",The Vegetarian
9917,5172,NaN,NaN,NaN,자미원국,2009-01-11,"[4, 5]",0,우선 작가의 사진이 다른 책보다 크다.\n\n무게감도 있지만 느낌이 좋다.\n\n무...,The Vegetarian
9918,5173,NaN,NaN,NaN,설탕,2008-12-17,"[4, 4]",0,정말로 유명한 책.\n\n채식주의자가 세상에 나온지는 아주. 아주 꽤 된 것 같은데...,The Vegetarian
9919,5174,NaN,NaN,NaN,secret,2005-11-04,"[5, 5]",1,과거 맨부커상 수상에 대한 수많은 기사와 뉴스에서 본 그 작품이기에 낯익은 듯 낯설...,The Vegetarian
...,...,...,...,...,...,...,...,...,...,...
13898,9153,NaN,NaN,NaN,솔이마루마마,2007-07-08,"[5, 5]",13,"바리데기 - 황석영\n아,,,뭐라 할까.그냥 감동적이다.라고 하기엔 나의 표현력이 ...",Princess Bari
13899,9154,NaN,NaN,NaN,진달래,2007-07-06,"[5, 5]",53,"정말 아름다운 작품이다. <오래된 정원>의 강렬한 사랑과 이념의 정수 이후, 진흙 ...",Princess Bari
13900,9155,NaN,NaN,NaN,romee21,2007-07-05,"[5, 4]",1,가제본된 책을 받는 순간 온몸에 떨림이 전해져 왔다. 마치 영화 시나리오를 받은 신...,Princess Bari
13901,9156,NaN,NaN,NaN,노부타,2007-07-05,"[4, 4]",0,어릴적에 그리스 로마 신화를 수십번도 더 읽은 기억이 있습니다. \n하지만 바리데기...,Princess Bari
13902,9157,NaN,NaN,NaN,삼지닥나무,2007-07-05,"[5, 4]",27,좋은 책을 미리 만나게 되서 좋았습니다. 받자마자 바로 읽기 시작했는데\n손을 놓을...,Princess Bari

In [151]:
reviews_yes24=pd.concat([to9915,novalue])
reviews_yes24=reviews_yes24.sort_values(by=['Title_EN','Review_Date'],ascending=False).reset_index()
reviews_yes24

,level_0,index,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content,Title_EN
0,1525,274,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,gracegod77,2021-06-28,"[4, 4]",0,"이 책에는 쥐덫 뿐만 아니라, 다른 단편 추리소설들도 실려 있지만\n\n가장 재미있...",mousetrap
1,1517,418,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,g********7,2021-06-23,[4],0,아이와 함께 재밌게 보고 있어요. 역시 쥐덫이 제일 재밌어요,mousetrap
2,1514,419,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,s***8,2018-11-26,[4],0,다른 단편은 좀 아쉬웠지만 '쥐덫'은 좋았다,mousetrap
3,1527,275,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,jekim1215,2017-11-01,"[4, 4]",0,이미 애거서 크리스티의 작품을 여럿 읽어본 결과 예상했던 그녀만의 스타일 그대로재밌...,mousetrap
4,1524,420,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,j*******5,2017-10-19,[5],0,애거서 크리스티 단편선 손가락으로 추천을 눌를수 밖에 없는 별 5개짜리 작품,mousetrap
...,...,...,...,...,...,...,...,...,...,...,...
13898,9903,3944,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,H아이,2012-11-26,"[4, 4]",0,시간여행은 가능할까?자신 혹은 타인의 과거를 바꿈으로서 지금 사는 현재를 변화시킬수...,11/22/63 1
13899,9904,3945,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,몽쁘띠,2012-11-26,"[4, 4]",0,당신에게도 되돌리고 싶은 과거가 있는가?\n남들은 모르는..혼자만 타임슬립해서 과거...,11/22/63 1
13900,9897,3946,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,아잇,2012-11-13,"[5, 4]",0,"할리우드식 사르카즘이야 그렇다 치고, 스티븐 킹만의 악랄하고 무자비하게 긴 괄호 세...",11/22/63 1
13901,9905,3947,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,사이클론,2012-11-06,"[5, 5]",0,시간여행을 통해 과거를 바꿀 수 있다면 당신은 무엇을 할 것인가?\n\n\n \n ...,11/22/63 1
13902,9907,3948,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,봄볕조는병아리,2012-11-06,"[5, 5]",5,이제 새삼스러운 일도 아니지만 확실히 2000년의 9.11 이 미국 문화 전반에 가...,11/22/63 1

In [ ]:
#PULIZIA DEL CAMPO SHELVES

In [111]:
meta_ko=pd.read_csv("C:\\Users\\Fossati\\Desktop\\Tesi\\Dati\\Dati_SharedBooks\\Coreano\\Shared_Meta_KO_fin.csv")
meta_ko

,Unnamed: 0,Title,Title_EN,ISBN,Author,Auth_Sugg,Num_Rev_Yes,Num_Rev_ol_Yes,Num_Reviews_Naver,az_EN_link,...,Book_type,Shelves_Yes,Dist_Rat_Cont_Yes,Dist_Rat_Design_Yes,Overall_Rat_Yes,Num_Pages_Yes,Pub_Date_Yes,Overall_Rat_ol_Yes,Pub_Date_Naver,Overall_Rat_Naver
0,0,그리고 아무도 없었다,And there was no one.,9.788938e+12,애거사 크리스티,Agatha Christie,120.0,118.0,620.0,https://www.amazon.it/Then-There-Were-None/dp/...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,"['59%', '22%', '18%', '1%', '1%']","['49%', '28%', '19%', '2%', '2%']",8.6,272.0,2002.0,9.2,2002.05.25,8.70
1,1,봄에 나는 없었다,Absent in spring,9.788955e+12,애거사 크리스티,Agatha Christie,50.0,14.0,207.0,https://www.amazon.com/Absent-Spring-AGATHA-CH...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 영미소설 > 영미 장편소설'],"['58%', '38%', '4%', '0%', '0%']","['58%', '40%', '2%', '0%', '0%']",9.1,268.0,2014.0,9.6,2014.01.30,8.38
2,2,오리엔트 특급 살인,Orient Express Murder,9.788960e+12,애거사 크리스티,Agatha Christie,28.0,289.0,72.0,https://www.amazon.com/Murder-Orient-Express-A...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,"['64%', '32%', '4%', '0%', '0%']","['64%', '32%', '4%', '0%', '0%']",9.2,341.0,2013.0,9.8,2014.11.25,9.44
3,3,딸은 딸이다,Daughter is a daughter.,9.788955e+12,애거사 크리스티,Agatha Christie,13.0,3.0,58.0,https://www.amazon.com/Daughters-Daughter-Othe...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 영미소설 > 영미 장편소설'],"['46%', '38%', '15%', '0%', '0%']","['38%', '46%', '15%', '0%', '0%']",8.5,320.0,2014.0,9.4,2014.05.15,9.41
4,4,ABC 살인사건,ABC murder case,9.788938e+12,애거사 크리스티,Agatha Christie,20.0,7.0,47.0,https://www.amazon.com/b-c-Murders-Hercule-Poi...,...,도서,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,"['50%', '35%', '10%', '5%', '0%']","['30%', '40%', '25%', '5%', '0%']",8.3,282.0,2002.0,9.8,2002.05.25,8.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,130,NaN,Untold Night and Day,NaN,NaN,Bae Suah,NaN,NaN,NaN,https://www.amazon.com/gp/product/B07V3335HK/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,131,NaN,The plotter,NaN,NaN,Un-Su Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/1925603768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,132,NaN,I Have the Right to Destroy Myself,NaN,NaN,Young-ha Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/0156030802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,133,NaN,Diary of a murderer,NaN,NaN,Young-ha Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/1328545423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,134,NaN,Princess Bari,NaN,NaN,Hwang Sok-yong,NaN,NaN,NaN,https://www.amazon.com/gp/product/1859641741/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
meta_ko['Shelves_Yes']

0      ['카테고리 분류\n  국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...
1         ['카테고리 분류\n  국내도서 > 소설/시/희곡 > 영미소설 > 영미 장편소설']
2      ['카테고리 분류\n  국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...
3         ['카테고리 분류\n  국내도서 > 소설/시/희곡 > 영미소설 > 영미 장편소설']
4      ['카테고리 분류\n  국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...
                             ...
130                                                  NaN
131                                                  NaN
132                                                  NaN
133                                                  NaN
134                                                  NaN
Name: Shelves_Yes, Length: 135, dtype: object

In [116]:
import ast

category=[]
media=[]
tag=[]

for index,row in meta_ko.iterrows():
    shelves=meta_ko['Shelves_Yes'][index]
    try:
        shelves=shelves.apply(ast.literal_eval)
        cat=shelves[0]
        cat2=cat.split('\n')
        category.append(cat2[1:])  #perchè il primo è sempre category
    except:
        category.append('error')
        
    try:
    
      if len(shelves) > 1:
    
    
        if shelves[1].split('\n')[0] == '수상내역 및 미디어 추천 분류':
            med=shelves[1]
            media.append(med[1:])
            tag.append('error')

            
        elif shelves[1].split('\n')[0] == '태그 분류':
            ta=shelves[1]
            tag.append(ta[1:])
            media.append('error')
            
        else:
            tag.append('error')
            media.append('error')
    
      else:
        tag.append('error')
        media.append('error')
        
    except:
        tag.append('error')
        media.append('error')
        

            
        
print(len(category))
print(len(media))
print(len(tag))    

#ora che abbiamo risytrutturato la colonna shelves integriamo il file di metadati e lo risalviamo

meta_ko['Shelves_Category']=category
meta_ko['Shelves_Media']=media
meta_ko['Shelves_Tags']=tag
meta_ko2=meta_ko.drop('Shelves_Yes',axis=1)
meta_ko2

135
135
135

,Unnamed: 0,Title,Title_EN,ISBN,Author,Auth_Sugg,Num_Rev_Yes,Num_Rev_ol_Yes,Num_Reviews_Naver,az_EN_link,...,Dist_Rat_Design_Yes,Overall_Rat_Yes,Num_Pages_Yes,Pub_Date_Yes,Overall_Rat_ol_Yes,Pub_Date_Naver,Overall_Rat_Naver,Shelves_Category,Shelves_Media,Shelves_Tags
0,0,그리고 아무도 없었다,And there was no one.,9.788938e+12,애거사 크리스티,Agatha Christie,120.0,118.0,620.0,https://www.amazon.it/Then-There-Were-None/dp/...,...,"['49%', '28%', '19%', '2%', '2%']",8.6,272.0,2002.0,9.2,2002.05.25,8.70,error,error,error
1,1,봄에 나는 없었다,Absent in spring,9.788955e+12,애거사 크리스티,Agatha Christie,50.0,14.0,207.0,https://www.amazon.com/Absent-Spring-AGATHA-CH...,...,"['58%', '40%', '2%', '0%', '0%']",9.1,268.0,2014.0,9.6,2014.01.30,8.38,error,error,error
2,2,오리엔트 특급 살인,Orient Express Murder,9.788960e+12,애거사 크리스티,Agatha Christie,28.0,289.0,72.0,https://www.amazon.com/Murder-Orient-Express-A...,...,"['64%', '32%', '4%', '0%', '0%']",9.2,341.0,2013.0,9.8,2014.11.25,9.44,error,error,error
3,3,딸은 딸이다,Daughter is a daughter.,9.788955e+12,애거사 크리스티,Agatha Christie,13.0,3.0,58.0,https://www.amazon.com/Daughters-Daughter-Othe...,...,"['38%', '46%', '15%', '0%', '0%']",8.5,320.0,2014.0,9.4,2014.05.15,9.41,error,error,error
4,4,ABC 살인사건,ABC murder case,9.788938e+12,애거사 크리스티,Agatha Christie,20.0,7.0,47.0,https://www.amazon.com/b-c-Murders-Hercule-Poi...,...,"['30%', '40%', '25%', '5%', '0%']",8.3,282.0,2002.0,9.8,2002.05.25,8.14,error,error,error
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,130,NaN,Untold Night and Day,NaN,NaN,Bae Suah,NaN,NaN,NaN,https://www.amazon.com/gp/product/B07V3335HK/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,error,error,error
131,131,NaN,The plotter,NaN,NaN,Un-Su Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/1925603768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,error,error,error
132,132,NaN,I Have the Right to Destroy Myself,NaN,NaN,Young-ha Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/0156030802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,error,error,error
133,133,NaN,Diary of a murderer,NaN,NaN,Young-ha Kim,NaN,NaN,NaN,https://www.amazon.com/gp/product/1328545423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,error,error,error
134,134,NaN,Princess Bari,NaN,NaN,Hwang Sok-yong,NaN,NaN,NaN,https://www.amazon.com/gp/product/1859641741/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,error,error,error

In [ ]:
#per ora rimandiamo il discorso
#il genere volendo si può annotare a mano per 135 libri

In [ ]:
#PULIZIA REVIEWS

In [126]:
union_yes2['Review_Content'][11118]

'주변에 참 많은 지영이들이 있다. 82년생들이 살았던 시절 즈음에 살았던 나와 내 주변의 지영이들도 책 속의 지영이와 별반 다를 것이 없다. 제목에 끌려 무슨 내용일까하면서 시작했던 책. 열었던 그 날 3시간만에 끝냈다. 어떻게 될까? 책 속의 지영이는 지금 다른 지영이들과 다른 삶을 살고 있겠지라고 기대했었는데 마무리는 사실 조금 실망이었다. 그냥 내 주변의 지영이들의 이야기를 읽은 듯한.. 내 주변 친구들의 평범한 삶을 읽은 듯한.. 내 삶을 조용히 한 번 되돌아 본 듯한.. 그런 느낌.. 읽고 나서 여운이 남는 책이기도 했다. 그래서 내 주변 지영이들에게 "너의 이야기니 한 번 보지 그래?"라고 이야기 해 주었다.'

In [ ]:
# caratteri speciali trovati:

#\xa0
#\n 
#\n\xa0\nps
#\xa089

#meglio tenere tutto e valutare poi

In [152]:
reviews_yes24.columns

Index(['level_0', 'index', 'Genere', 'Title', 'ISBN', 'Username',
       'Review_Date', 'Review_Ratings', 'Num_Likes', 'Review_Content',
       'Title_EN'],
      dtype='object')

In [153]:
reviews2_yes24=reviews_yes24.drop(['index','level_0'],axis=1)
reviews2_yes24

,Genere,Title,ISBN,Username,Review_Date,Review_Ratings,Num_Likes,Review_Content,Title_EN
0,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,gracegod77,2021-06-28,"[4, 4]",0,"이 책에는 쥐덫 뿐만 아니라, 다른 단편 추리소설들도 실려 있지만\n\n가장 재미있...",mousetrap
1,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,g********7,2021-06-23,[4],0,아이와 함께 재밌게 보고 있어요. 역시 쥐덫이 제일 재밌어요,mousetrap
2,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,s***8,2018-11-26,[4],0,다른 단편은 좀 아쉬웠지만 '쥐덫'은 좋았다,mousetrap
3,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,jekim1215,2017-11-01,"[4, 4]",0,이미 애거서 크리스티의 작품을 여럿 읽어본 결과 예상했던 그녀만의 스타일 그대로재밌...,mousetrap
4,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n...,쥐덫,9.788938e+12,j*******5,2017-10-19,[5],0,애거서 크리스티 단편선 손가락으로 추천을 눌를수 밖에 없는 별 5개짜리 작품,mousetrap
...,...,...,...,...,...,...,...,...,...
13898,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,H아이,2012-11-26,"[4, 4]",0,시간여행은 가능할까?자신 혹은 타인의 과거를 바꿈으로서 지금 사는 현재를 변화시킬수...,11/22/63 1
13899,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,몽쁘띠,2012-11-26,"[4, 4]",0,당신에게도 되돌리고 싶은 과거가 있는가?\n남들은 모르는..혼자만 타임슬립해서 과거...,11/22/63 1
13900,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,아잇,2012-11-13,"[5, 4]",0,"할리우드식 사르카즘이야 그렇다 치고, 스티븐 킹만의 악랄하고 무자비하게 긴 괄호 세...",11/22/63 1
13901,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,사이클론,2012-11-06,"[5, 5]",0,시간여행을 통해 과거를 바꿀 수 있다면 당신은 무엇을 할 것인가?\n\n\n \n ...,11/22/63 1
13902,['카테고리 분류\n 국내도서 > 소설/시/희곡 > 장르소설 > SF\n 국내도...,11/22/63 1,9.788960e+12,봄볕조는병아리,2012-11-06,"[5, 5]",5,이제 새삼스러운 일도 아니지만 확실히 2000년의 9.11 이 미국 문화 전반에 가...,11/22/63 1

In [154]:

#export file


reviews2_yes24.to_csv('Yes24_shared_reviews.csv')